### ISSUE TITLE
macOS Monteray can break local docker registries

### ISSUE THREAD

**Issue by ajslater** [mkantor/docker-pushmi-pullyu#28]
macOS Monteray has started listening on port 5000 if System Preferences > Sharing > AirPlay Receiver is on
I'd noticed this previously with the RogueAmoeba AirFoil Satellite program that does the same thing.
https://developer.apple.com/forums/thread/682332

Probably it would be good to be able to configure pushmi-pullyu to use the registry on another port.

I made a little script to automate a workaround for this:
https://github.com/ajslater/toggle_airplay_receiver

**Comment by mkantor** [comment]
Good call, thanks for filing an issue about this.

Instead of adding another CLI option to configure this I'm thinking of using `--publish-all` when running the registry to bind to a random available port. What do you think?

**Comment by mkantor** [comment]
How does #29 look?

**Comment by ajslater** [comment]
`--publish-all` seems like an elegant solution, I like it.

**Comment by mkantor** [comment]
@ajslater thanks again for pointing this out!
